"""File storage abstraction (Tier 5.1).

Call sites deal only with `save_image()` / `open_stream()` / `delete()` and a
`storage_key`; the actual backend (local filesystem today, S3/MinIO later) lives
behind this module so swapping it never touches routers.

Image handling on save:
  - validate MIME against config allow-list
  - enforce the size cap
  - **strip EXIF** (re-encode pixels only) — a work photo's embedded GPS is the
    employee's location, i.e. personal data that must not be persisted
  - generate a small thumbnail for list views on slow field connections
"""

from __future__ import annotations

import io
import os
import uuid
from dataclasses import dataclass
from typing import BinaryIO, Optional

from fastapi import HTTPException

from app.config import settings

try:
    from PIL import Image
    _PIL_OK = True
except Exception:  # pragma: no cover - Pillow is a declared dependency
    _PIL_OK = False


THUMBNAIL_MAX = (400, 400)
_EXT = {"image/jpeg": ".jpg", "image/png": ".png", "image/webp": ".webp"}


@dataclass
class StoredImage:
    storage_key: str
    thumbnail_key: Optional[str]
    mime_type: str
    size_bytes: int


# ---------------------------------------------------------------------------
# Local filesystem backend
# ---------------------------------------------------------------------------

def _base_dir() -> str:
    d = os.path.abspath(settings.STORAGE_DIR)
    os.makedirs(d, exist_ok=True)
    return d


def _abs_path(storage_key: str) -> str:
    base = _base_dir()
    # Reject traversal — keys are generated by us, but never trust a path.
    full = os.path.abspath(os.path.join(base, storage_key))
    if not full.startswith(base + os.sep):
        raise HTTPException(status_code=400, detail="Invalid storage key")
    return full


def _write(storage_key: str, data: bytes) -> None:
    path = _abs_path(storage_key)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def save_image(raw: bytes, mime_type: str) -> StoredImage:
    """Validate, strip EXIF, thumbnail, and persist an uploaded image."""
    allowed = settings.allowed_upload_mime_list
    if mime_type not in allowed:
        raise HTTPException(
            status_code=422,
            detail=f"Unsupported file type {mime_type!r}. Allowed: {', '.join(allowed)}",
        )
    max_bytes = settings.MAX_UPLOAD_MB * 1024 * 1024
    if len(raw) > max_bytes:
        raise HTTPException(status_code=413, detail=f"File exceeds {settings.MAX_UPLOAD_MB} MB limit")
    if not raw:
        raise HTTPException(status_code=422, detail="Empty file")

    if not _PIL_OK:  # pragma: no cover
        raise HTTPException(status_code=500, detail="Image processing unavailable (Pillow not installed)")

    # Decode → this both verifies it is a real image (not a renamed executable)
    # and lets us re-encode without the original EXIF block.
    try:
        img = Image.open(io.BytesIO(raw))
        img.load()
    except Exception:
        raise HTTPException(status_code=422, detail="File is not a valid image")

    fmt = {"image/jpeg": "JPEG", "image/png": "PNG", "image/webp": "WEBP"}[mime_type]
    folder = uuid.uuid4().hex[:2]              # shard so one dir isn't unbounded
    name = uuid.uuid4().hex
    ext = _EXT[mime_type]
    storage_key = f"{folder}/{name}{ext}"
    thumb_key = f"{folder}/{name}_thumb{ext}"

    # Re-encode without EXIF. For JPEG/WebP we drop the exif kwarg entirely; PNG
    # has no EXIF block to carry.
    clean = io.BytesIO()
    save_img = img.convert("RGB") if (mime_type == "image/jpeg" and img.mode in ("RGBA", "P")) else img
    save_img.save(clean, format=fmt)
    clean_bytes = clean.getvalue()
    _write(storage_key, clean_bytes)

    thumb = img.copy()
    thumb.thumbnail(THUMBNAIL_MAX)
    tbuf = io.BytesIO()
    (thumb.convert("RGB") if (mime_type == "image/jpeg" and thumb.mode in ("RGBA", "P")) else thumb).save(tbuf, format=fmt)
    _write(thumb_key, tbuf.getvalue())

    return StoredImage(
        storage_key=storage_key,
        thumbnail_key=thumb_key,
        mime_type=mime_type,
        size_bytes=len(clean_bytes),
    )


def open_stream(storage_key: str) -> BinaryIO:
    path = _abs_path(storage_key)
    if not os.path.exists(path):
        raise HTTPException(status_code=404, detail="File not found")
    return open(path, "rb")


def delete(storage_key: Optional[str]) -> None:
    if not storage_key:
        return
    try:
        path = _abs_path(storage_key)
        if os.path.exists(path):
            os.remove(path)
    except HTTPException:
        pass


def has_exif(raw: bytes) -> bool:
    """Test helper: True if the bytes still carry EXIF metadata."""
    if not _PIL_OK:  # pragma: no cover
        return False
    try:
        img = Image.open(io.BytesIO(raw))
        exif = img.getexif()
        return bool(exif)
    except Exception:
        return False
