#!/bin/sh
# RestaurantOps — database (and uploads) backup with retention.
#
# Writes a pg_dump custom-format archive (compressed, restorable with
# scripts/restore_db.sh / pg_restore) to $BACKUP_DIR/daily/. On Sundays the
# dump is also copied to $BACKUP_DIR/weekly/. Old files beyond the retention
# counts are deleted.
#
# Connection uses the standard libpq variables: PGHOST, PGPORT, PGUSER,
# PGPASSWORD, PGDATABASE. POSIX sh so it runs in the postgres:17-alpine image
# (the `db-backup` compose service) as well as on a plain host.
#
# Environment:
#   BACKUP_DIR        where backups go               (default /backups)
#   KEEP_DAILY        daily dumps to keep             (default 7)
#   KEEP_WEEKLY       weekly dumps to keep            (default 4)
#   UPLOADS_DIR       if set, also tar this directory (work-order photos)
#
# Exit codes: 0 = ok, non-zero = failure (nothing half-written is left behind).

set -eu

BACKUP_DIR="${BACKUP_DIR:-/backups}"
KEEP_DAILY="${KEEP_DAILY:-7}"
KEEP_WEEKLY="${KEEP_WEEKLY:-4}"
DB_NAME="${PGDATABASE:-restaurantops}"

STAMP="$(date +%Y-%m-%d_%H%M%S)"
DAILY_DIR="$BACKUP_DIR/daily"
WEEKLY_DIR="$BACKUP_DIR/weekly"
mkdir -p "$DAILY_DIR" "$WEEKLY_DIR"

log() { echo "[backup] $(date -Iseconds) $*"; }

# Keep the newest $2 files matching $3 in directory $1, delete the rest.
prune() {
    dir="$1"; keep="$2"; pattern="$3"
    # shellcheck disable=SC2012 — names are generated by this script (no spaces).
    ls -1t "$dir"/$pattern 2>/dev/null | tail -n +"$((keep + 1))" | while read -r old; do
        rm -f "$old"
        log "pruned $old"
    done
}

# --- Database ---------------------------------------------------------------
DUMP="$DAILY_DIR/$DB_NAME-$STAMP.dump"
TMP="$DUMP.partial"
UPLOADS_TMP=""
trap 'rm -f "$TMP" "$UPLOADS_TMP" 2>/dev/null || true' EXIT

log "dumping database $DB_NAME"
pg_dump --format=custom --compress=6 --no-owner --file="$TMP" "$DB_NAME"
# Rename only after pg_dump succeeded, so a failed run never leaves a
# truncated file that looks like a valid backup.
mv "$TMP" "$DUMP"
log "wrote $DUMP ($(du -h "$DUMP" | cut -f1))"

# --- Uploads (optional) -----------------------------------------------------
if [ -n "${UPLOADS_DIR:-}" ] && [ -d "$UPLOADS_DIR" ]; then
    UPLOADS="$DAILY_DIR/uploads-$STAMP.tar.gz"
    UPLOADS_TMP="$UPLOADS.partial"
    tar -czf "$UPLOADS_TMP" -C "$UPLOADS_DIR" .
    mv "$UPLOADS_TMP" "$UPLOADS"
    log "wrote $UPLOADS ($(du -h "$UPLOADS" | cut -f1))"
fi

# --- Weekly copy (Sunday) ---------------------------------------------------
if [ "$(date +%u)" = "7" ]; then
    cp "$DUMP" "$WEEKLY_DIR/"
    [ -n "${UPLOADS:-}" ] && cp "$UPLOADS" "$WEEKLY_DIR/"
    log "copied to weekly"
fi

# --- Retention --------------------------------------------------------------
prune "$DAILY_DIR" "$KEEP_DAILY" "$DB_NAME-*.dump"
prune "$DAILY_DIR" "$KEEP_DAILY" "uploads-*.tar.gz"
prune "$WEEKLY_DIR" "$KEEP_WEEKLY" "$DB_NAME-*.dump"
prune "$WEEKLY_DIR" "$KEEP_WEEKLY" "uploads-*.tar.gz"

log "done"
